/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zenzet_cipher_crypto_Mycrypt */

#ifndef _Included_com_zenzet_cipher_crypto_Mycrypt
#define _Included_com_zenzet_cipher_crypto_Mycrypt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zenzet_cipher_crypto_Mycrypt
 * Method:    LOCKetAESCFB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zenzet_cipher_crypto_Mycrypt_LOCKetAESCFB
  (JNIEnv *, jclass);

/*
 * Class:     com_zenzet_cipher_crypto_Mycrypt
 * Method:    LKTGenerateKeyPair
 * Signature: (I)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_zenzet_cipher_crypto_Mycrypt_LKTGenerateKeyPair
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_zenzet_cipher_crypto_Mycrypt
 * Method:    getInstance
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_zenzet_cipher_crypto_Mycrypt_getInstance
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_zenzet_cipher_crypto_Mycrypt
 * Method:    digestUpdate
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_com_zenzet_cipher_crypto_Mycrypt_digestUpdate
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_zenzet_cipher_crypto_Mycrypt
 * Method:    digestFinal
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_zenzet_cipher_crypto_Mycrypt_digestFinal
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
